sudo: false
dist: trusty
language: node_js

node_js:
  - "9.5"

services:
  - docker

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - npm install -g --silent @angular/cli

script: 
  - ng test --watch=false
  - ng e2e
  - ng build --prod

notifications:
  email:
    on_failure: always
    on_success: change
