version: "3"
services:

  db:
    image: postgres:10.4
    ports:
      - "5432:5432"

  sqs:
    image: pakohan/elasticmq
    hostname: sqs
    ports:
      - 9324:9324

  django:
    container_name: ngx_django
    hostname: django
    env_file:
      - docker/dev/docker.env
    build:
      context: ./
      dockerfile: docker/dev/django/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - "db"
      - "sqs"

  worker:
    env_file:
      - docker/dev/docker.env
    build:
      context: ./
      dockerfile: docker/dev/worker/Dockerfile
    depends_on:
      - "django"

  angularjs:
    container_name: evalai_ngx
    hostname: angularjs
    build:
      context: ./
      dockerfile: docker/dev/angularjs/Dockerfile
    environment:
      ANGULAR_ENV: development
    ports:
      - "8888:4200"
      - "4200:4200"
    depends_on:
      - "django"
    volumes:
    - .:/code
    - /code/node_modules
